Dashboard alerts page
Zhi-704/Railway-Tracker pull request #98
Opened 2024-07-24 16:46 UTC by fm1psy

Closes issue #30 

The incidents_alerts page now lets users give their details and subscribe to an operator

2024-07-24 17:56 UTC, FarihaChoudhury commented on dashboard/pages/incident_alerts.py
> +    """"""
I think you forgot these docstrings

2024-07-24 17:56 UTC, FarihaChoudhury commented on dashboard/pages/incident_alerts.py
> +    """"""
and the ones in the functions below

2024-07-25 09:45 UTC, A-Faris commented on dashboard/pages/daily_report.py
I'm jus assuming your auto-formatter did these changes

2024-07-25 09:46 UTC, A-Faris commented on dashboard/pages/incident_alerts.py
> +    st.write("""Subscribe to an Operator Alert using your phone number,
```suggestion
    st.write("""Subscribe to an Operator Alert using your phone number,
```

2024-07-25 09:47 UTC, A-Faris commented on dashboard/pages/incident_alerts.py
> +    st.write("""Subscribe to an Operator Alert using your phone number,
remove trailing whitespace

2024-07-25 09:49 UTC, A-Faris commented on dashboard/pages/incident_alerts.py
> +    """"""
Docstrings empty

2024-07-25 09:50 UTC, A-Faris commented on dashboard/pages/incident_alerts.py
> +    except:
```suggestion
    except Exception as e:  # pylint: disable=broad-exception-caught
```

2024-07-25 09:50 UTC, A-Faris commented on dashboard/pages/incident_alerts.py
> +    except:
```suggestion
    except Exception:  # pylint: disable=broad-exception-caught
```

2024-07-25 09:51 UTC, A-Faris requested changes
Looks good just needs pylinting

2024-07-25 11:03 UTC, fm1psy commented on dashboard/pages/daily_report.py
Looks like that is the case yeah

2024-07-25 11:40 UTC, A-Faris approved these changes, later dismissed
Looks great

2024-07-25 14:29 UTC, A-Faris approved these changes, later dismissed
Looks good

2024-07-26 08:51 UTC, FarihaChoudhury submitted a review, later dismissed

2024-07-26 08:52 UTC, FarihaChoudhury approved these changes, later dismissed
beautiful

2024-07-26 10:14 UTC, Zhi-704 approved these changes

2024-07-26 10:15 UTC, merged